START
MOVER   DREG,     ='7'
MACRO
INCR_D  &MEM_VAL, &INCR_VAL=, &REG=AREG
MOVER   &REG,     &MEM_VAL
ADD     &REG,     &INCR_VAL
MOVEM   &REG,     &MEM_VAL
MEND
ADD     DREG,     ='7'
MACRO
INCR_D  AREA,     &INCR_VAL=3
MOVEM   BREG,     &THIRD
MOVER   BREG,     &THIRD
ADD     BREG,     &THIRD
MEND
COMPUTE AREA,     3
END
